package com.agentdroid

import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalClipboardManager
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.AnnotatedString
import androidx.compose.ui.text.input.KeyboardType
import androidx.compose.ui.unit.dp
import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import androidx.lifecycle.viewmodel.compose.viewModel
import androidx.navigation.NavHostController
import androidx.navigation.compose.*
import androidx.room.Room
import com.agentdroid.core.ai.*
import com.agentdroid.core.model.*
import com.agentdroid.data.database.*
import com.agentdroid.security.SecureSecretStore
import kotlinx.coroutines.Job
import kotlinx.coroutines.flow.*
import kotlinx.coroutines.launch
import java.util.UUID

class MainActivity : ComponentActivity() { override fun onCreate(savedInstanceState: Bundle?) { super.onCreate(savedInstanceState); setContent { AgentDroidApp() } } }
private object RoomProvider { lateinit var context: android.content.Context; private var instance: AgentDatabase? = null; fun get(): AgentDatabase = instance ?: Room.databaseBuilder(context, AgentDatabase::class.java, "agentdroid.db").build().also { instance = it } }

private class AgentViewModel : ViewModel() {
    private val db by lazy { RoomProvider.get() }; private val secrets by lazy { SecureSecretStore(RoomProvider.context) }; private val registry = ProviderRegistry(listOf(OpenAiProvider(), AnthropicProvider(), GeminiProvider(), OpenRouterProvider(), CompatibleProvider(), FakeAiProvider())); private val now get() = System.currentTimeMillis()
    val conversations = db.conversations().observeAll().stateIn(viewModelScope, SharingStarted.WhileSubscribed(5_000), emptyList()); val providers = db.providers().observeAll().stateIn(viewModelScope, SharingStarted.WhileSubscribed(5_000), emptyList()); val workspaces = db.workspaces().observeAll().stateIn(viewModelScope, SharingStarted.WhileSubscribed(5_000), emptyList()); val memory = db.memory().observeAll().stateIn(viewModelScope, SharingStarted.WhileSubscribed(5_000), emptyList()); val skills = db.skills().observeAll().stateIn(viewModelScope, SharingStarted.WhileSubscribed(5_000), emptyList())
    var selectedConversation by mutableStateOf<String?>(null); var phase by mutableStateOf(ChatPhase.IDLE); var errorMessage by mutableStateOf<String?>(null); private var activeJob: Job? = null
    fun messages(id: String): Flow<List<MessageEntity>> = db.messages().observe(id)
    fun newConversation(onCreated: (String) -> Unit = {}) = viewModelScope.launch { val id = UUID.randomUUID().toString(); db.conversations().upsert(ConversationEntity(id, "New conversation", now, now)); selectedConversation = id; onCreated(id) }
    fun addProvider(name: String, kind: ProviderKind, key: String, baseUrl: String, model: String, onSaved: () -> Unit) { if (name.isBlank() || (key.isBlank() && kind != ProviderKind.COMPATIBLE) || (kind == ProviderKind.COMPATIBLE && baseUrl.isBlank())) { errorMessage = "invalid"; return }; viewModelScope.launch { val alias = "secret_${UUID.randomUUID()}"; if (key.isNotBlank()) secrets.put(alias, key); db.providers().upsert(ProviderConfigEntity(kind.name.lowercase(), name, kind.name, baseUrl.ifBlank { null }, model.ifBlank { null }, alias, null, null, null, "{}", true)); onSaved() } }
    fun testProvider(entity: ProviderConfigEntity, result: (ProviderTestResult) -> Unit) = viewModelScope.launch { val kind = ProviderKind.valueOf(entity.kind); val config = ProviderConfig(entity.id, entity.name, kind, entity.baseUrl, entity.modelId, entity.secretAlias); result(registry.get(kind)?.testConnection(config, entity.secretAlias?.let(secrets::get).orEmpty()) ?: ProviderTestResult(false, entity.name, error = AppError.Provider("Provider not registered"))) }
    fun send(id: String, text: String, provider: ProviderConfigEntity?) { if (text.isBlank() || phase == ChatPhase.STREAMING) return; activeJob?.cancel(); activeJob = viewModelScope.launch { val user = MessageEntity(UUID.randomUUID().toString(), id, "USER", text, MessageStatus.COMPLETED.name, now, now); db.messages().upsert(user); db.conversations().rename(id, text.take(40), now); val assistantId = UUID.randomUUID().toString(); db.messages().upsert(MessageEntity(assistantId, id, "ASSISTANT", "", MessageStatus.STREAMING.name, now, now)); if (provider == null) { phase = ChatPhase.FAILED; errorMessage = "provider"; return@launch }; val kind = ProviderKind.valueOf(provider.kind); val config = ProviderConfig(provider.id, provider.name, kind, provider.baseUrl, provider.modelId, provider.secretAlias); val implementation = registry.get(kind) ?: run { phase = ChatPhase.FAILED; errorMessage = "provider"; return@launch }; phase = ChatPhase.SUBMITTING; var response = ""; val history = db.messages().observe(id).first().map { ChatMessage(if (it.role == "USER") MessageRole.USER else MessageRole.ASSISTANT, it.content) }; implementation.streamChat(ChatRequest(history, provider.modelId.orEmpty()), config, provider.secretAlias?.let(secrets::get).orEmpty()).collect { event -> when (event) { AiStreamEvent.Started -> phase = ChatPhase.STREAMING; is AiStreamEvent.TextDelta -> { phase = ChatPhase.STREAMING; response += event.text; db.messages().upsert(MessageEntity(assistantId, id, "ASSISTANT", response, MessageStatus.STREAMING.name, now, now)) }; AiStreamEvent.Completed -> { phase = ChatPhase.COMPLETED; db.messages().upsert(MessageEntity(assistantId, id, "ASSISTANT", response, MessageStatus.COMPLETED.name, now, now)) }; is AiStreamEvent.Error -> { phase = ChatPhase.FAILED; errorMessage = event.error.userMessage; db.messages().upsert(MessageEntity(assistantId, id, "ASSISTANT", response, MessageStatus.FAILED.name, now, now, errorJson = event.error.technicalMessage)) }; else -> Unit } } } }
    fun stop() { activeJob?.cancel(); phase = ChatPhase.CANCELLED }; fun addWorkspace(name: String, description: String) = viewModelScope.launch { db.workspaces().upsert(WorkspaceEntity(UUID.randomUUID().toString(), name, description, now, now)) }; fun addMemory(title: String, content: String) = viewModelScope.launch { db.memory().upsert(MemoryEntryEntity(UUID.randomUUID().toString(), "GLOBAL", null, title, content, true, now, now)) }; fun addSkill(name: String, description: String, instructions: String) = viewModelScope.launch { db.skills().upsert(SkillEntity(UUID.randomUUID().toString(), name, description, instructions, true, "GLOBAL", null, now, now)) }
}

@Composable fun AgentDroidApp() { val context = LocalContext.current; LaunchedEffect(Unit) { RoomProvider.context = context.applicationContext }; val vm: AgentViewModel = viewModel(); var dark by remember { mutableStateOf(false) }; AgentTheme(dark) { val nav = rememberNavController(); val route = nav.currentBackStackEntryAsState().value?.destination?.route; Scaffold(bottomBar = { NavigationBar { listOf("home" to Icons.Default.Home, "chat" to Icons.Default.Chat, "workspaces" to Icons.Default.Folder, "more" to Icons.Default.MoreHoriz).forEach { (itemRoute, icon) -> NavigationBarItem(selected = route == itemRoute, onClick = { nav.navigate(itemRoute) { launchSingleTop = true } }, icon = { Icon(icon, null) }, label = { Text(when (itemRoute) { "home" -> stringResource(R.string.home); "chat" -> stringResource(R.string.chat); "workspaces" -> stringResource(R.string.workspaces); else -> stringResource(R.string.more) }) }) } } }) { padding -> NavHost(nav, "home", Modifier.padding(padding)) { composable("home") { HomeScreen(nav, vm) }; composable("chat") { ChatScreen(nav, vm) }; composable("workspaces") { WorkspacesScreen(vm) }; composable("more") { MoreScreen(nav) }; composable("providers") { ProvidersScreen(nav, vm) }; composable("models") { ModelsScreen(vm) }; composable("settings") { SettingsScreen { dark = it } }; composable("memory") { MemoryScreen(vm) }; composable("skills") { SkillsScreen(vm) }; composable("conversations") { ConversationsScreen(nav, vm) }; composable("addProvider") { AddProviderScreen(nav, vm) } } } } }
@Composable private fun AgentTheme(dark: Boolean, content: @Composable () -> Unit) { MaterialTheme(colorScheme = if (dark) darkColorScheme() else lightColorScheme(primary = Color(0xFF6750A4)), content = content) }
@OptIn(ExperimentalMaterial3Api::class) @Composable private fun Top(title: String, nav: NavHostController? = null, action: (() -> Unit)? = null) { TopAppBar(title = { Text(title) }, navigationIcon = { if (nav != null) IconButton({ nav.popBackStack() }) { Icon(Icons.Default.ArrowBack, null) } }, actions = { if (action != null) IconButton(action) { Icon(Icons.Default.Add, null) } }) }

@Composable private fun HomeScreen(nav: NavHostController, vm: AgentViewModel) { val conversations by vm.conversations.collectAsState(); LazyColumn(Modifier.fillMaxSize().padding(20.dp), verticalArrangement = Arrangement.spacedBy(16.dp)) { item { Text("AgentDroid", style = MaterialTheme.typography.headlineMedium); Text(stringResource(R.string.greeting), style = MaterialTheme.typography.titleLarge); Text(stringResource(R.string.what_to_do), color = MaterialTheme.colorScheme.onSurfaceVariant) }; item { Button({ vm.newConversation { nav.navigate("chat") } }, Modifier.fillMaxWidth()) { Icon(Icons.Default.Add, null); Spacer(Modifier.width(8.dp)); Text(stringResource(R.string.new_chat)) } }; item { Text(stringResource(R.string.recent), style = MaterialTheme.typography.titleMedium) }; items(conversations.take(6)) { conversation -> ElevatedCard({ vm.selectedConversation = conversation.id; nav.navigate("chat") }, Modifier.fillMaxWidth()) { Column(Modifier.padding(16.dp)) { Text(conversation.title, style = MaterialTheme.typography.titleMedium); Text(android.text.format.DateUtils.getRelativeTimeSpanString(conversation.updatedAt).toString(), color = MaterialTheme.colorScheme.onSurfaceVariant) } } } } }
@Composable private fun ChatScreen(nav: NavHostController, vm: AgentViewModel) { val id = vm.selectedConversation; val providers by vm.providers.collectAsState(); var input by remember { mutableStateOf("") }; val messages = if (id == null) emptyList() else vm.messages(id).collectAsState(initial = emptyList()).value; Column(Modifier.fillMaxSize()) { Top(stringResource(R.string.chat), nav, vm::newConversation); if (id == null) Box(Modifier.weight(1f).fillMaxWidth(), Alignment.Center) { Column(horizontalAlignment = Alignment.CenterHorizontally) { Text(stringResource(R.string.no_messages)); Button({ vm.newConversation() }) { Text(stringResource(R.string.new_chat)) } } } else LazyColumn(Modifier.weight(1f).fillMaxWidth().padding(horizontal = 12.dp), verticalArrangement = Arrangement.spacedBy(10.dp)) { items(messages) { MessageBubble(it) } }; if (vm.errorMessage != null) Text(vm.errorMessage.orEmpty(), modifier = Modifier.padding(12.dp), color = MaterialTheme.colorScheme.error); Row(Modifier.padding(12.dp), verticalAlignment = Alignment.Bottom) { OutlinedTextField(input, { input = it }, Modifier.weight(1f), placeholder = { Text(stringResource(R.string.composer_hint)) }, maxLines = 5); Spacer(Modifier.width(8.dp)); if (vm.phase == ChatPhase.STREAMING) IconButton(vm::stop) { Icon(Icons.Default.Stop, stringResource(R.string.stop)) } else IconButton({ if (id != null) { vm.send(id, input, providers.firstOrNull()); input = "" } }) { Icon(Icons.Default.Send, stringResource(R.string.send)) } } } }
@Composable private fun MessageBubble(message: MessageEntity) { val clipboard = LocalClipboardManager.current; val isUser = message.role == "USER"; Surface(color = if (isUser) MaterialTheme.colorScheme.primaryContainer else MaterialTheme.colorScheme.surfaceVariant, shape = MaterialTheme.shapes.large, modifier = Modifier.fillMaxWidth()) { Column(Modifier.padding(14.dp)) { Text(if (isUser) "You" else "AgentDroid", style = MaterialTheme.typography.labelMedium); MarkdownText(message.content); Row(Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.End) { IconButton({ clipboard.setText(AnnotatedString(message.content)) }) { Icon(Icons.Default.ContentCopy, stringResource(R.string.copy)) } } } } }
@Composable private fun MarkdownText(text: String) { Column(Modifier.fillMaxWidth()) { text.split("\n").forEach { line -> Text(line, Modifier.fillMaxWidth(), fontFamily = if (line.startsWith("```") || line.startsWith("    ")) androidx.compose.ui.text.font.FontFamily.Monospace else androidx.compose.ui.text.font.FontFamily.Default) } } }
@Composable private fun MoreScreen(nav: NavHostController) { LazyColumn(Modifier.fillMaxSize().padding(16.dp), verticalArrangement = Arrangement.spacedBy(10.dp)) { item { Text(stringResource(R.string.more), style = MaterialTheme.typography.headlineSmall) }; item { ListTile(stringResource(R.string.providers), Icons.Default.Cloud) { nav.navigate("providers") } }; item { ListTile(stringResource(R.string.models), Icons.Default.List) { nav.navigate("models") } }; item { ListTile(stringResource(R.string.conversations), Icons.Default.History) { nav.navigate("conversations") } }; item { ListTile(stringResource(R.string.memory), Icons.Default.Memory) { nav.navigate("memory") } }; item { ListTile(stringResource(R.string.skills), Icons.Default.Star) { nav.navigate("skills") } }; item { ListTile(stringResource(R.string.settings), Icons.Default.Settings) { nav.navigate("settings") } } } }
@Composable private fun ListTile(title: String, icon: androidx.compose.ui.graphics.vector.ImageVector, onClick: () -> Unit) { ElevatedCard(onClick = onClick, modifier = Modifier.fillMaxWidth()) { ListItem(headlineContent = { Text(title) }, leadingContent = { Icon(icon, null) }, trailingContent = { Icon(Icons.Default.ChevronRight, null) }) } }
@Composable private fun ProvidersScreen(nav: NavHostController, vm: AgentViewModel) { val providers by vm.providers.collectAsState(); Column { Top(stringResource(R.string.providers), nav) { nav.navigate("addProvider") }; if (providers.isEmpty()) Box(Modifier.fillMaxSize(), Alignment.Center) { Text(stringResource(R.string.no_provider)) } else LazyColumn(Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(10.dp)) { items(providers) { provider -> ElevatedCard(Modifier.fillMaxWidth()) { Column(Modifier.padding(16.dp)) { Text(provider.name, style = MaterialTheme.typography.titleLarge); Text(provider.kind); Text(provider.modelId ?: stringResource(R.string.not_configured), color = MaterialTheme.colorScheme.onSurfaceVariant); Button({ vm.testProvider(provider) {} }) { Text(stringResource(R.string.test_connection)) } } } } } } }
@Composable private fun AddProviderScreen(nav: NavHostController, vm: AgentViewModel) { var name by remember { mutableStateOf("") }; var key by remember { mutableStateOf("") }; var base by remember { mutableStateOf("") }; var model by remember { mutableStateOf("") }; var kind by remember { mutableStateOf(ProviderKind.OPENAI) }; Column(Modifier.fillMaxSize().padding(20.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) { Top(stringResource(R.string.add_provider), nav); OutlinedTextField(name, { name = it }, Modifier.fillMaxWidth(), label = { Text(stringResource(R.string.provider_name)) }); Text(stringResource(R.string.select_model)); Row(horizontalArrangement = Arrangement.spacedBy(4.dp)) { ProviderKind.values().forEach { p -> FilterChip(kind == p, { kind = p }, label = { Text(p.name.lowercase()) }) } }; OutlinedTextField(key, { key = it }, Modifier.fillMaxWidth(), label = { Text(stringResource(R.string.api_key)) }, keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Password)); OutlinedTextField(base, { base = it }, Modifier.fillMaxWidth(), label = { Text(stringResource(R.string.base_url)) }); OutlinedTextField(model, { model = it }, Modifier.fillMaxWidth(), label = { Text(stringResource(R.string.model_id)) }); Button({ vm.addProvider(name, kind, key, base, model) { nav.popBackStack() } }, Modifier.fillMaxWidth()) { Text(stringResource(R.string.save)) } } }
@Composable private fun ModelsScreen(vm: AgentViewModel) { val providers by vm.providers.collectAsState(); LazyColumn(Modifier.fillMaxSize().padding(16.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) { item { Text(stringResource(R.string.models), style = MaterialTheme.typography.headlineSmall) }; items(providers) { Text("${it.name} • ${it.modelId ?: "—"}") } } }
@Composable private fun ConversationsScreen(nav: NavHostController, vm: AgentViewModel) { val conversations by vm.conversations.collectAsState(); LazyColumn(Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) { item { Top(stringResource(R.string.conversations), nav) }; items(conversations) { conversation -> ElevatedCard({ vm.selectedConversation = conversation.id; nav.navigate("chat") }, Modifier.fillMaxWidth()) { ListItem(headlineContent = { Text(conversation.title) }, supportingContent = { Text(android.text.format.DateUtils.getRelativeTimeSpanString(conversation.updatedAt).toString()) }) } } } }
@Composable private fun WorkspacesScreen(vm: AgentViewModel) { val workspaces by vm.workspaces.collectAsState(); var show by remember { mutableStateOf(false) }; if (show) EditDialog(stringResource(R.string.create_workspace), stringResource(R.string.workspace_name), stringResource(R.string.description), { n, d -> vm.addWorkspace(n, d); show = false }, { show = false }); Column(Modifier.fillMaxSize().padding(16.dp)) { Row(Modifier.fillMaxWidth(), Arrangement.SpaceBetween) { Text(stringResource(R.string.workspaces), style = MaterialTheme.typography.headlineSmall); IconButton({ show = true }) { Icon(Icons.Default.Add, null) } }; LazyColumn(verticalArrangement = Arrangement.spacedBy(10.dp)) { items(workspaces) { workspace -> ElevatedCard(Modifier.fillMaxWidth()) { ListItem(headlineContent = { Text(workspace.name) }, supportingContent = { Text(workspace.description) }) } } } } }
@Composable private fun MemoryScreen(vm: AgentViewModel) { val entries by vm.memory.collectAsState(); var show by remember { mutableStateOf(false) }; if (show) EditDialog(stringResource(R.string.add_memory), stringResource(R.string.provider_name), stringResource(R.string.description), { n, d -> vm.addMemory(n, d); show = false }, { show = false }); Column(Modifier.fillMaxSize().padding(16.dp)) { Row(Modifier.fillMaxWidth(), Arrangement.SpaceBetween) { Text(stringResource(R.string.memory), style = MaterialTheme.typography.headlineSmall); IconButton({ show = true }) { Icon(Icons.Default.Add, null) } }; LazyColumn { items(entries) { entry -> ListItem(headlineContent = { Text(entry.title) }, supportingContent = { Text(entry.content) }, trailingContent = { Switch(entry.enabled, {}) }) } } } }
@Composable private fun SkillsScreen(vm: AgentViewModel) { val skills by vm.skills.collectAsState(); var show by remember { mutableStateOf(false) }; if (show) EditDialog(stringResource(R.string.add_skill), stringResource(R.string.provider_name), stringResource(R.string.description), { n, d -> vm.addSkill(n, d, d); show = false }, { show = false }); Column(Modifier.fillMaxSize().padding(16.dp)) { Row(Modifier.fillMaxWidth(), Arrangement.SpaceBetween) { Text(stringResource(R.string.skills), style = MaterialTheme.typography.headlineSmall); IconButton({ show = true }) { Icon(Icons.Default.Add, null) } }; LazyColumn { items(skills) { skill -> ListItem(headlineContent = { Text(skill.name) }, supportingContent = { Text(skill.description) }, trailingContent = { Switch(skill.enabled, {}) }) } } } }
@Composable private fun EditDialog(title: String, first: String, second: String, onSave: (String, String) -> Unit, onCancel: () -> Unit) { var a by remember { mutableStateOf("") }; var b by remember { mutableStateOf("") }; AlertDialog(onDismissRequest = onCancel, title = { Text(title) }, text = { Column(verticalArrangement = Arrangement.spacedBy(8.dp)) { OutlinedTextField(a, { a = it }, label = { Text(first) }); OutlinedTextField(b, { b = it }, label = { Text(second) }) } }, confirmButton = { Button({ if (a.isNotBlank()) onSave(a, b) }) { Text(stringResource(R.string.save)) } }, dismissButton = { TextButton(onCancel) { Text(stringResource(R.string.cancel)) } }) }
@Composable private fun SettingsScreen(onDark: (Boolean) -> Unit) { var dark by remember { mutableStateOf(false) }; Column(Modifier.fillMaxSize().padding(20.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) { Text(stringResource(R.string.settings), style = MaterialTheme.typography.headlineSmall); Text(stringResource(R.string.appearance), style = MaterialTheme.typography.titleMedium); ListItem(headlineContent = { Text(stringResource(R.string.dark)) }, trailingContent = { Switch(dark, { dark = it; onDark(it) }) }); Text(stringResource(R.string.language), style = MaterialTheme.typography.titleMedium); ListItem(headlineContent = { Text(stringResource(R.string.system)) }); ListItem(headlineContent = { Text(stringResource(R.string.arabic)) }); ListItem(headlineContent = { Text(stringResource(R.string.english)) }) } }
