package com.agentdroid.core.ai

import com.agentdroid.core.model.*
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow
import kotlinx.coroutines.withContext
import kotlinx.serialization.json.*
import okhttp3.*
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.RequestBody.Companion.toRequestBody
import java.io.IOException
import java.util.concurrent.TimeUnit

private val json = Json { ignoreUnknownKeys = true }
private val client = OkHttpClient.Builder().connectTimeout(30, TimeUnit.SECONDS).readTimeout(0, TimeUnit.MILLISECONDS).build()

abstract class BaseHttpProvider(override val id: String, override val displayName: String, override val capabilities: ProviderCapabilities): AiProvider {
    protected open fun endpoint(config: ProviderConfig, path: String) = (config.baseUrl?.trimEnd('/') ?: defaultBase).plus(path)
    protected open val defaultBase = "https://api.openai.com/v1"
    protected open fun request(config: ProviderConfig, secret: String, path: String, method: String = "GET", body: String? = null): Request { val b = Request.Builder().url(endpoint(config,path)).header("Accept","application/json"); if (secret.isNotBlank()) b.header("Authorization","Bearer $secret"); config.organizationId?.let { b.header("OpenAI-Organization",it) }; config.customHeaders.forEach { (k,v) -> b.header(k,v) }; if (body != null) b.method(method, body.toRequestBody("application/json".toMediaType())); return b.build() }
    protected suspend fun execute(req: Request): Response = withContext(Dispatchers.IO) { client.newCall(req).execute() }
    protected fun errorFor(code: Int, body: String): AppError = when(code) { 401,403 -> AppError.Authentication("HTTP $code: $body", "Invalid API key"); 429 -> AppError.RateLimit("HTTP 429: $body"); in 400..499 -> AppError.Provider("HTTP $code: $body"); else -> AppError.Network("HTTP $code: $body") }
    override suspend fun testConnection(config: ProviderConfig, secret: String): ProviderTestResult { val started = System.currentTimeMillis(); return try { execute(request(config,secret,"/models")).use { r -> if (!r.isSuccessful) ProviderTestResult(false,displayName,error = errorFor(r.code,r.body?.string().orEmpty())) else ProviderTestResult(true,displayName,modelCount = runCatching { json.parseToJsonElement(r.body?.string().orEmpty()).jsonObject["data"]?.jsonArray?.size }.getOrNull(),latencyMs = System.currentTimeMillis()-started,streamingSupported = capabilities.streaming) } } catch(e: IOException) { ProviderTestResult(false,displayName,error=AppError.Network(e.javaClass.simpleName)) } }
    override suspend fun listModels(config: ProviderConfig, secret: String): Result<List<AiModel>> = runCatching { execute(request(config,secret,"/models")).use { r -> if(!r.isSuccessful) error(errorFor(r.code,r.body?.string().orEmpty())); val arr = json.parseToJsonElement(r.body?.string().orEmpty()).jsonObject["data"]?.jsonArray ?: JsonArray(emptyList()); arr.mapNotNull { el -> el.jsonObject["id"]?.jsonPrimitive?.content?.let { AiModel(it,it,capabilities) } } } }
    override fun streamChat(request: ChatRequest, config: ProviderConfig, secret: String): Flow<AiStreamEvent> = flow { emit(AiStreamEvent.Started); val payload = buildJsonObject { put("model",request.model); put("stream",true); putJsonArray("messages") { request.messages.forEach { addJsonObject { put("role",it.role.name.lowercase()); put("content",it.content) } } } }.toString(); try { execute(this@BaseHttpProvider.request(config,secret,"/chat/completions","POST",payload)).use { r -> if(!r.isSuccessful){ emit(AiStreamEvent.Error(errorFor(r.code,r.body?.string().orEmpty()))); return@flow }; val reader = r.body?.charStream()?.buffered(); if (reader != null) { while (true) { val line = reader.readLine() ?: break; val clean=line.removePrefix("data:").trim(); if(clean.isBlank() || clean=="[DONE]") continue; runCatching { json.parseToJsonElement(clean).jsonObject["choices"]?.jsonArray?.firstOrNull()?.jsonObject?.get("delta")?.jsonObject?.get("content")?.jsonPrimitive?.content }.getOrNull()?.let { emit(AiStreamEvent.TextDelta(it)) } } }; emit(AiStreamEvent.Completed) } } catch(e: IOException) { emit(AiStreamEvent.Error(AppError.Network(e.message ?: "Network failure"))) } }
}
class OpenAiProvider: BaseHttpProvider("openai","OpenAI",ProviderCapabilities(modelListing=true,toolCalling=true,vision=true))
class OpenRouterProvider: BaseHttpProvider("openrouter","OpenRouter",ProviderCapabilities(modelListing=true,toolCalling=true,vision=true)) { override val defaultBase="https://openrouter.ai/api/v1"; override fun request(config: ProviderConfig, secret: String, path: String, method: String, body: String?): Request = super.request(config,secret,path,method,body).newBuilder().apply { config.siteUrl?.let { header("HTTP-Referer",it) }; config.appName?.let { header("X-Title",it) } }.build() }
class CompatibleProvider: BaseHttpProvider("compatible","OpenAI-Compatible",ProviderCapabilities(modelListing=true))
class AnthropicProvider: BaseHttpProvider("anthropic","Anthropic",ProviderCapabilities(modelListing=false,vision=true)) { override val defaultBase="https://api.anthropic.com/v1"; override fun request(config: ProviderConfig, secret: String, path: String, method: String, body: String?): Request = Request.Builder().url(endpoint(config,path)).header("x-api-key",secret).header("anthropic-version","2023-06-01").header("Accept","application/json").apply { if(body!=null) method(method,body.toRequestBody("application/json".toMediaType())) else method(method,null) }.build() }
class GeminiProvider: BaseHttpProvider("gemini","Google Gemini",ProviderCapabilities(modelListing=true,vision=true)) { override val defaultBase="https://generativelanguage.googleapis.com/v1beta"; override fun request(config: ProviderConfig, secret: String, path: String, method: String, body: String?): Request = Request.Builder().url(endpoint(config,path)+"?key=$secret").header("Accept","application/json").apply { if(body!=null) method(method,body.toRequestBody("application/json".toMediaType())) else method(method,null) }.build() }
class FakeAiProvider: AiProvider { override val id="fake"; override val displayName="Fake provider"; override val capabilities=ProviderCapabilities(modelListing=true); override suspend fun testConnection(config:ProviderConfig,secret:String)=ProviderTestResult(true,displayName,1,12,true); override suspend fun listModels(config:ProviderConfig,secret:String)=Result.success(listOf(AiModel("fake-model","Fake model",capabilities))); override fun streamChat(request:ChatRequest,config:ProviderConfig,secret:String)=flow { emit(AiStreamEvent.Started); "This is a local test response. دعم العربية وEnglish.".forEach { kotlinx.coroutines.delay(8); emit(AiStreamEvent.TextDelta(it.toString())) }; emit(AiStreamEvent.Completed) } }
